//
// Created by ste on 17/03/24.
//

#ifndef SCPD_PROJECT_INCLUDE_DATA_STRUCTURES_PARTICLE_H_
#define SCPD_PROJECT_INCLUDE_DATA_STRUCTURES_PARTICLE_H_

#endif //SCPD_PROJECT_INCLUDE_DATA_STRUCTURES_PARTICLE_H_
